**Importing Libraries **

In [13]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

In [3]:
df=pd.read_csv('/content/drive/MyDrive/Data sets/Social_Network_Ads.csv')
df

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

**Columns**

In [5]:
print("Columns in dataset:", df.columns)

Columns in dataset: Index(['User ID', 'Gender', 'Age', 'EstimatedSalary', 'Purchased'], dtype='object')


**Droping User id as it is not useful for prediction.**

In [6]:
if 'User ID' in df.columns:
    df.drop('User ID', axis=1, inplace=True)

**Encoding Label  (Male = 1, Female = 0).**

In [7]:
le = LabelEncoder()
df['Gender'] = le.fit_transform(df['Gender'])

**Setting target and features sepration **

In [8]:
X = df[['Age', 'EstimatedSalary']]
y = df['Purchased']

** Applying StandardScaler for feature normalization.**

In [9]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

**Training and splitting Data Set.**

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.25, random_state=0)

**tranning using guassian naive bayes Theorem**

In [14]:
gnb = GaussianNB()
gnb.fit(X_train, y_train)

GaussianNB()

**Now using KNN theorem.**

In [16]:
knn3 = KNeighborsClassifier(n_neighbors=3)
knn3.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [17]:
knn5 = KNeighborsClassifier(n_neighbors=5)
knn5.fit(X_train, y_train)

KNeighborsClassifier()

In [18]:
knn7 = KNeighborsClassifier(n_neighbors=7)
knn7.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=7)

**Train dession Tree with gini.**

In [19]:
gini = DecisionTreeClassifier(criterion='gini', random_state=0)
gini.fit(X_train, y_train)

DecisionTreeClassifier(random_state=0)

**Train Dession-Tree with entropy.**

In [22]:
entropy = DecisionTreeClassifier(criterion='entropy', random_state=0)
entropy.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

**Now we are going to evaluate the Model using functions for accuracy , precision , recall-score, and F1-score.**

In [21]:
def evaluate_model(model, X_test, y_test, model_name):
    y_pred = model.predict(X_test)
    print(f"\n--- {model_name} ---")
    print("Accuracy:", accuracy_score(y_test, y_pred))
    print("Precision:", precision_score(y_test, y_pred, average='weighted'))
    print("Recall:", recall_score(y_test, y_pred, average='weighted'))
    print("F1 Score:", f1_score(y_test, y_pred, average='weighted'))
    print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

In [23]:
evaluate_model(gnb, X_test, y_test, "Naive Bayes")

evaluate_model(knn3, X_test, y_test, "KNN (k=3)")
evaluate_model(knn5, X_test, y_test, "KNN (k=5)")
evaluate_model(knn7, X_test, y_test, "KNN (k=7)")

evaluate_model(gini, X_test, y_test, "Decision Tree (Gini)")
evaluate_model(entropy, X_test, y_test, "Decision Tree (Entropy)")


--- Naive Bayes ---
Accuracy: 0.9
Precision: 0.8996031746031747
Recall: 0.9
F1 Score: 0.8980952380952381
Confusion Matrix:
 [[65  3]
 [ 7 25]]

--- KNN (k=3) ---
Accuracy: 0.93
Precision: 0.9307643600180914
Recall: 0.93
F1 Score: 0.9302792022792024
Confusion Matrix:
 [[64  4]
 [ 3 29]]

--- KNN (k=5) ---
Accuracy: 0.93
Precision: 0.9307643600180914
Recall: 0.93
F1 Score: 0.9302792022792024
Confusion Matrix:
 [[64  4]
 [ 3 29]]

--- KNN (k=7) ---
Accuracy: 0.93
Precision: 0.9307643600180914
Recall: 0.93
F1 Score: 0.9302792022792024
Confusion Matrix:
 [[64  4]
 [ 3 29]]

--- Decision Tree (Gini) ---
Accuracy: 0.9
Precision: 0.9023172905525847
Recall: 0.9
F1 Score: 0.900768882858435
Confusion Matrix:
 [[62  6]
 [ 4 28]]

--- Decision Tree (Entropy) ---
Accuracy: 0.91
Precision: 0.9137582417582418
Recall: 0.91
F1 Score: 0.9109998877791493
Confusion Matrix:
 [[62  6]
 [ 3 29]]
